import json
import os
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc, roc_curve
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import argparse

# Custom Dataset Class, compatible with raw_data.json generated by previous scripts
class TextDetectDataset(Dataset):
    def __init__(self, data_path):
        # Load dataset json file
        with open(data_path, "r", encoding="utf-8") as f:
            self.data = json.load(f)
        # Verify required data fields exist
        assert "original" in self.data and "rewritten" in self.data
        # Ensure equal number of human and AI text samples
        assert len(self.data["original"]) == len(self.data["rewritten"])
        self.human_texts = self.data["original"]
        self.ai_texts = self.data["rewritten"]
        # Combine all texts for inference
        self.all_texts = self.human_texts + self.ai_texts
        # Label definition: 0 for human-written text, 1 for AI-generated text
        self.labels = [0] * len(self.human_texts) + [1] * len(self.ai_texts)

    def __len__(self):
        # Return total number of text samples
        return len(self.all_texts)

    def __getitem__(self, idx):
        # Return single text sample and its corresponding label
        return {
            "text": self.all_texts[idx],
            "label": self.labels[idx]
        }

# Perform batch inference and return predicted probability of AI class
def batch_inference(model, tokenizer, texts, device, max_len=512):
    # Switch model to evaluation mode (disable dropout & gradient computation)
    model.eval()
    # Tokenize input texts
    inputs = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_len,
        return_tensors="pt"
    ).to(device)
    # Disable gradient calculation to save memory and speed up inference
    with torch.no_grad():
        outputs = model(**inputs)
        # Convert logits to probability distribution via softmax
        probs = torch.softmax(outputs.logits, dim=-1)
    # Return probability of class 1 (AI-generated text)
    return probs[:, 1].cpu().numpy()

def run_roberta_detect(args):
    # Select computing device (GPU if available, otherwise CPU)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")

    # Load RoBERTa tokenizer and binary classification model
    print(f"Loading RoBERTa detection model: {args.roberta_model_name}")
    tokenizer = AutoTokenizer.from_pretrained(args.roberta_model_name, cache_dir=args.cache_dir)
    model = AutoModelForSequenceClassification.from_pretrained(
        args.roberta_model_name,
        num_labels=2,
        cache_dir=args.cache_dir
    ).to(device)

    # Load evaluation dataset
    print(f"Loading dataset from {args.dataset_file}")
    eval_dataset = TextDetectDataset(args.dataset_file)
    eval_loader = DataLoader(eval_dataset, batch_size=args.batch_size, shuffle=False)

    all_scores = []  # Store predicted AI probability of all samples
    all_labels = []   # Store ground truth labels of all samples

    # Iterate over dataloader for full dataset inference
    for batch in tqdm(eval_loader, desc="RoBERTa Detect Inference"):
        texts = batch["text"]
        labels = batch["label"].numpy()
        pred_scores = batch_inference(model, tokenizer, texts, device)
        all_scores.extend(pred_scores.tolist())
        all_labels.extend(labels.tolist())

    y_true = np.array(all_labels)
    y_scores = np.array(all_scores)

    # Calculate core evaluation metrics
    auroc = roc_auc_score(y_true, y_scores)
    fpr, tpr, _ = roc_curve(y_true, y_scores)
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    pr_auc = auc(recall, precision)

    # Organize quantitative evaluation results
    result_dict = {
        "auroc": float(auroc),
        "pr_auc": float(pr_auc),
        "human_mean_score": float(np.mean(y_scores[y_true == 0])),
        "ai_mean_score": float(np.mean(y_scores[y_true == 1]))
    }

    # Create subplots for ROC curve and Precision-Recall curve
    plt.figure(figsize=(14, 6))
    # Plot ROC Curve
    plt.subplot(1, 2, 1)
    plt.plot(fpr, tpr, lw=2, color="darkorange", label=f"AUROC = {auroc:.4f}")
    plt.plot([0, 1], [0, 1], linestyle="--", color="navy")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve")
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)

    # Plot Precision-Recall Curve
    plt.subplot(1, 2, 2)
    plt.plot(recall, precision, lw=2, color="#1f77b4", label=f"PR-AUC = {pr_auc:.4f}")
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title("Precision-Recall Curve")
    plt.legend(loc="lower left")
    plt.grid(alpha=0.3)

    plt.tight_layout()
    # Create output directory if it does not exist
    os.makedirs(args.output_file, exist_ok=True)
    # Save curve figure with high resolution
    plt.savefig(os.path.join(args.output_file, "roberta_eval_curves.png"), dpi=300)
    plt.close()

    # Save numerical evaluation metrics to JSON file
    json_save_path = os.path.join(args.output_file, "roberta_result.json")
    with open(json_save_path, "w", encoding="utf-8") as f:
        json.dump(result_dict, f, indent=4, ensure_ascii=False)

    # Print final evaluation results to console
    print("\n==== RoBERTa Detection Evaluation Result ====")
    print(f"AUROC Score: {auroc:.4f}")
    print(f"PR-AUC Score: {pr_auc:.4f}")
    print(f"Average score of human text: {result_dict['human_mean_score']:.4f}")
    print(f"Average score of AI-generated text: {result_dict['ai_mean_score']:.4f}")
    print(f"All outputs saved to: {args.output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="RoBERTa-based AI vs Human Text Detector Evaluation")

    # Output directory for figures and metric files
    parser.add_argument('--output_file', type=str, default="./results/roberta_eval",
                        help="Directory to save evaluation figure and result json file")
    # Short identifier for current dataset experiment
    parser.add_argument('--dataset', type=str, default="data",
                        help="Short name tag for target evaluation dataset")
    # File path of the raw dataset json
    parser.add_argument('--dataset_file', type=str, default="./aspo/data_my/diff_method_val_data/data",
                        help="Full path of raw_data.json evaluation dataset")
    # RoBERTa model path or huggingface name
    parser.add_argument('--roberta_model_name', type=str, default="roberta-base",
                        help="RoBERTa checkpoint name or local folder path for detection")
    # Batch size for model inference
    parser.add_argument('--batch_size', type=int, default=8,
                        help="Batch size used during model forward inference")
    # Random seed for full experiment reproducibility
    parser.add_argument('--seed', type=int, default=0,
                        help="Global random seed to reproduce experimental results")
    # Hardware device for model computation
    parser.add_argument('--device', type=str, default="cuda",
                        help="Computation device, available options: cuda / cpu")
    # Cache directory for downloaded pre-trained model weights
    parser.add_argument('--cache_dir', type=str, default="./local_model",
                        help="Local cache folder for storing pre-trained model weights")

    args = parser.parse_args()

    # Fix all random seeds to guarantee reproducible results
    import random
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(args.seed)

    run_roberta_detect(args)